{{- if .Values.destinationRule.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
  - labels:
      version: {{ .Values.env.name }}
    name: v1
  trafficPolicy:
    portLevelSettings:
    - port:
        number: {{ .Values.service.dstPort }}
      loadBalancer:
        simple: {{ .Values.destinationRule.loadBalanceMode }}
{{- end }}