apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.srcPort }}
      targetPort: {{ .Values.service.dstPort }}
      protocol: TCP
      name: {{ .Values.service.name | default "http" }}
  selector:
    {{- include "base.selectorLabels" . | nindent 4 }}
